// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Use environment variables for Supabase configuration
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  "https://nfwthtzncrnyvwqsqncw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5md3RodHpuY3JueXZ3cXNxbmN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MjQ1MDYsImV4cCI6MjA2NjEwMDUwNn0.yQAKWXoIpwASHmRJo3G5a5F2WoZkIwV7TrfXtg0cN_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
